// <auto-generated />
using System;
using DDD_Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DDD_Data.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20210914153134_Uf_City_PostalCode_Migration")]
    partial class Uf_City_PostalCode_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("DDD_Domain.Entities.CityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IbgeCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<Guid>("UfId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IbgeCode");

                    b.HasIndex("UfId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("DDD_Domain.Entities.PostalCodeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<Guid>("CityId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("PostalCode");

                    b.ToTable("PostalCode");
                });

            modelBuilder.Entity("DDD_Domain.Entities.UfEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FederatedUnit")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FederatedUnit")
                        .IsUnique();

                    b.ToTable("Uf");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22ffbd18-cdb9-45cc-97b0-51e97700bf71"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3293),
                            FederatedUnit = "AC",
                            Name = "Acre"
                        },
                        new
                        {
                            Id = new Guid("7cc33300-586e-4be8-9a4d-bd9f01ee9ad8"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3301),
                            FederatedUnit = "AL",
                            Name = "Alagoas"
                        },
                        new
                        {
                            Id = new Guid("cb9e6888-2094-45ee-bc44-37ced33c693a"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3304),
                            FederatedUnit = "AM",
                            Name = "Amazonas"
                        },
                        new
                        {
                            Id = new Guid("409b9043-88a4-4e86-9cca-ca1fb0d0d35b"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3307),
                            FederatedUnit = "AP",
                            Name = "Amapá"
                        },
                        new
                        {
                            Id = new Guid("5abca453-d035-4766-a81b-9f73d683a54b"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3309),
                            FederatedUnit = "BA",
                            Name = "Bahia"
                        },
                        new
                        {
                            Id = new Guid("5ff1b59e-11e7-414d-827e-609dc5f7e333"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3311),
                            FederatedUnit = "CE",
                            Name = "Ceará"
                        },
                        new
                        {
                            Id = new Guid("bd08208b-bfca-47a4-9cd0-37e4e1fa5006"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3313),
                            FederatedUnit = "DF",
                            Name = "Distrito Federal"
                        },
                        new
                        {
                            Id = new Guid("c623f804-37d8-4a19-92c1-67fd162862e6"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3316),
                            FederatedUnit = "ES",
                            Name = "Espírito Santo"
                        },
                        new
                        {
                            Id = new Guid("837a64d3-c649-4172-a4e0-2b20d3c85224"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3318),
                            FederatedUnit = "GO",
                            Name = "Goiás"
                        },
                        new
                        {
                            Id = new Guid("57a9e9f7-9aea-40fe-a783-65d4feb59fa8"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3320),
                            FederatedUnit = "MA",
                            Name = "Maranhão"
                        },
                        new
                        {
                            Id = new Guid("27f7a92b-1979-4e1c-be9d-cd3bb73552a8"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3323),
                            FederatedUnit = "MG",
                            Name = "Minas Gerais"
                        },
                        new
                        {
                            Id = new Guid("3739969c-fd8a-4411-9faa-3f718ca85e70"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3325),
                            FederatedUnit = "MS",
                            Name = "Mato Grosso do Sul"
                        },
                        new
                        {
                            Id = new Guid("29eec4d3-b061-427d-894f-7f0fecc7f65f"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3327),
                            FederatedUnit = "MT",
                            Name = "Mato Grosso"
                        },
                        new
                        {
                            Id = new Guid("8411e9bc-d3b2-4a9b-9d15-78633d64fc7c"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3330),
                            FederatedUnit = "PA",
                            Name = "Pará"
                        },
                        new
                        {
                            Id = new Guid("1109ab04-a3a5-476e-bdce-6c3e2c2badee"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3332),
                            FederatedUnit = "PB",
                            Name = "Paraíba"
                        },
                        new
                        {
                            Id = new Guid("ad5969bd-82dc-4e23-ace2-d8495935dd2e"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3334),
                            FederatedUnit = "PE",
                            Name = "Pernambuco"
                        },
                        new
                        {
                            Id = new Guid("f85a6cd0-2237-46b1-a103-d3494ab27774"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3336),
                            FederatedUnit = "PI",
                            Name = "Piauí"
                        },
                        new
                        {
                            Id = new Guid("1dd25850-6270-48f8-8b77-2f0f079480ab"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3339),
                            FederatedUnit = "PR",
                            Name = "Paraná"
                        },
                        new
                        {
                            Id = new Guid("43a0f783-a042-4c46-8688-5dd4489d2ec7"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3341),
                            FederatedUnit = "RJ",
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = new Guid("542668d1-50ba-4fca-bbc3-4b27af108ea3"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3343),
                            FederatedUnit = "RN",
                            Name = "Rio Grande do Norte"
                        },
                        new
                        {
                            Id = new Guid("924e7250-7d39-4e8b-86bf-a8578cbf4002"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3345),
                            FederatedUnit = "RO",
                            Name = "Rondônia"
                        },
                        new
                        {
                            Id = new Guid("9fd3c97a-dc68-4af5-bc65-694cca0f2869"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3348),
                            FederatedUnit = "RR",
                            Name = "Roraima"
                        },
                        new
                        {
                            Id = new Guid("88970a32-3a2a-4a95-8a18-2087b65f59d1"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3350),
                            FederatedUnit = "RS",
                            Name = "Rio Grande do Sul"
                        },
                        new
                        {
                            Id = new Guid("b81f95e0-f226-4afd-9763-290001637ed4"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3352),
                            FederatedUnit = "SC",
                            Name = "Santa Catarina"
                        },
                        new
                        {
                            Id = new Guid("fe8ca516-034f-4249-bc5a-31c85ef220ea"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3355),
                            FederatedUnit = "SE",
                            Name = "Sergipe"
                        },
                        new
                        {
                            Id = new Guid("e7e416de-477c-4fa3-a541-b5af5f35ccf6"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3357),
                            FederatedUnit = "SP",
                            Name = "São Paulo"
                        },
                        new
                        {
                            Id = new Guid("971dcb34-86ea-4f92-989d-064f749e23c9"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 968, DateTimeKind.Utc).AddTicks(3360),
                            FederatedUnit = "TO",
                            Name = "Tocantins"
                        });
                });

            modelBuilder.Entity("DDD_Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60f7f1c1-81bd-44eb-90f3-6dd7a70f9a3d"),
                            CreatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 965, DateTimeKind.Utc).AddTicks(9926),
                            Email = "admin@mail.com",
                            Name = "Admin",
                            UpdatedAt = new DateTime(2021, 9, 14, 15, 31, 33, 966, DateTimeKind.Utc).AddTicks(1415)
                        });
                });

            modelBuilder.Entity("DDD_Domain.Entities.CityEntity", b =>
                {
                    b.HasOne("DDD_Domain.Entities.UfEntity", "Uf")
                        .WithMany("Cities")
                        .HasForeignKey("UfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uf");
                });

            modelBuilder.Entity("DDD_Domain.Entities.PostalCodeEntity", b =>
                {
                    b.HasOne("DDD_Domain.Entities.CityEntity", "City")
                        .WithMany("PostalCodes")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("DDD_Domain.Entities.CityEntity", b =>
                {
                    b.Navigation("PostalCodes");
                });

            modelBuilder.Entity("DDD_Domain.Entities.UfEntity", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
