// <auto-generated />
using System;
using DDD_Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DDD_Data.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20210909165024_UserMigration")]
    partial class UserMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("DDD_Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3e34bb5c-30a2-4353-a0da-f5fc5af372f0"),
                            CreatedAt = new DateTime(2021, 9, 9, 16, 50, 24, 683, DateTimeKind.Utc).AddTicks(7315),
                            Email = "admin@mail.com",
                            Name = "Admin",
                            UpdatedAt = new DateTime(2021, 9, 9, 16, 50, 24, 683, DateTimeKind.Utc).AddTicks(8336)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
